platform :ios, '15.6'

target 'CastNow' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'WebRTC-SDK'
  pod 'Starscream', '~> 4.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
    end
  end
end