-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQJmCddLaVy43OpHQ
SzIsJIJfNMi3CoMprtuGzzgRPY6gCgYIKoZIzj0DAQehRANCAAQaYZVvfXc6HrRZ
nZOnrI/cyT+QGsDBXYb2PhQWdHwBB+aczfoxRQ0WEh05Sk7K8Jd6zsnKbrks/2Te
CHmKWnKC
-----END PRIVATE KEY-----